# Generated by Django 2.0.1 on 2018-04-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0002_auto_20180406_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='submitted_answers',
        ),
        migrations.AddField(
            model_name='room',
            name='submitted_answers',
            field=models.ManyToManyField(blank=True, to='trivia.SubmittedAnswer'),
        ),
    ]
