# Generated by Django 2.0.1 on 2018-04-06 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0003_auto_20180406_0447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submittedanswer',
            old_name='order',
            new_name='rank',
        ),
    ]
