# Generated by Django 2.0.1 on 2018-03-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0003_auto_20180306_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='rounds',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='time',
            field=models.IntegerField(),
        ),
    ]
